import type {
  ArticleSelection,
  AuditEntry,
  Category,
  CmsUser,
  ContentItem,
  NewsStudioArticle,
} from "./types";

export const DEMO_PASSWORD = "mattr123";

export const SEED_USERS: CmsUser[] = [
  {
    id: "u-admin",
    email: "admin@dailymattr.com",
    fullName: "Aarav Mehta",
    role: "super_admin",
    languages: ["en"],
    states: [],
    isActive: true,
    avatarHue: 222,
  },
  {
    id: "u-editor",
    email: "editor@dailymattr.com",
    fullName: "Sravan P",
    role: "chief_editor",
    languages: ["en", "hi"],
    states: [],
    isActive: true,
    avatarHue: 262,
  },
  {
    id: "u-writer",
    email: "writer@dailymattr.com",
    fullName: "Nikita Rao",
    role: "writer",
    languages: ["en"],
    states: ["Telangana", "Andhra Pradesh"],
    isActive: true,
    avatarHue: 152,
  },
  {
    id: "u-qa",
    email: "qa@dailymattr.com",
    fullName: "Farhan Ali",
    role: "qa",
    languages: ["en"],
    states: [],
    isActive: true,
    avatarHue: 20,
  },
];

export const SEED_CATEGORIES: Category[] = [
  { slug: "india", name: "India", kind: null, sortOrder: 1, isActive: true },
  { slug: "world", name: "World", kind: null, sortOrder: 2, isActive: true },
  { slug: "politics", name: "Politics", kind: null, sortOrder: 3, isActive: true },
  { slug: "business", name: "Business", kind: null, sortOrder: 4, isActive: true },
  { slug: "technology", name: "Technology", kind: null, sortOrder: 5, isActive: true },
  { slug: "science", name: "Science", kind: null, sortOrder: 6, isActive: true },
  { slug: "sports", name: "Sports", kind: null, sortOrder: 7, isActive: true },
  { slug: "entertainment", name: "Entertainment", kind: null, sortOrder: 8, isActive: true },
];

const hoursAgo = (h: number) => new Date(Date.now() - h * 3600_000).toISOString();

const img = (seed: string) => `https://picsum.photos/seed/${seed}/640/400`;

export const SEED_NEWSSTUDIO: NewsStudioArticle[] = [
  {
    id: "ns-01",
    title: "Monsoon session opens with heated exchange over exam paper leaks",
    summary:
      "Parliament's monsoon session began with the Opposition demanding a debate on recurring exam paper leaks. The government said a new integrity framework for national tests will be tabled this week, while student groups continued protests in three states.",
    category: "Politics",
    source: "NDTV",
    imageUrl: img("parliament"),
    factScore: 96,
    factLabel: "FACT 96",
    sourceCount: 4,
    status: "approved",
    publishedAt: hoursAgo(3),
  },
  {
    id: "ns-02",
    title: "Chip startup halts signups as demand for new AI model overwhelms GPUs",
    summary:
      "Days after unveiling its most advanced model, a fast-growing AI lab paused new registrations citing GPU capacity limits. Analysts say the surge underlines how compute, not talent, is now the sector's tightest bottleneck.",
    category: "Technology",
    source: "India Today Tech",
    imageUrl: img("gpu"),
    factScore: 92,
    factLabel: "FACT 92",
    sourceCount: 3,
    status: "approved",
    publishedAt: hoursAgo(5),
  },
  {
    id: "ns-03",
    title: "Tanker attack in Strait of Hormuz raises freight and insurance costs",
    summary:
      "A strike on two tankers pushed war-risk premiums sharply higher and rerouted several shipments around the Cape. Officials said one crew member died; energy markets opened 2% up before easing by noon.",
    category: "World",
    source: "Hindustan Times",
    imageUrl: img("tanker"),
    factScore: 90,
    factLabel: "FACT 90",
    sourceCount: 5,
    status: "approved",
    publishedAt: hoursAgo(9),
  },
  {
    id: "ns-04",
    title: "RBI holds rates, signals patience on inflation glide path",
    summary:
      "The central bank kept the repo rate unchanged for a fourth straight meeting, citing sticky food inflation. Economists now expect the first cut no earlier than the December review, with growth projections held at 6.9%.",
    category: "Business",
    source: "Mint",
    imageUrl: img("rbi"),
    factScore: 97,
    factLabel: "FACT 97",
    sourceCount: 6,
    status: "approved",
    publishedAt: hoursAgo(12),
  },
  {
    id: "ns-05",
    title: "ISRO test-fires reusable lander engine ahead of lunar cargo mission",
    summary:
      "The space agency completed a full-duration burn of its throttleable lander engine, a key step toward the 2027 lunar cargo mission. Engineers called the test 'textbook', with reuse targeted across three flights.",
    category: "Science",
    source: "The Hindu",
    imageUrl: img("isro"),
    factScore: 95,
    factLabel: "FACT 95",
    sourceCount: 3,
    status: "approved",
    publishedAt: hoursAgo(18),
  },
  {
    id: "ns-06",
    title: "National monuments shrink under new order, legal challenges mount",
    summary:
      "A federal order reduced two protected monuments, drawing lawsuits from conservation groups and tribal nations within hours. Legal scholars expect the case to reach the Supreme Court next term.",
    category: "World",
    source: "India Today",
    imageUrl: img("monument"),
    factScore: 88,
    factLabel: "FACT 88",
    sourceCount: 4,
    status: "approved",
    publishedAt: hoursAgo(22),
  },
  {
    id: "ns-07",
    title: "T20 league final draws record streaming audience of 61 million",
    summary:
      "Sunday's final set a concurrent-viewership record as the underdogs chased 204 with an over to spare. Advertisers paid up to 40% more than last season for endgame slots, the broadcaster said.",
    category: "Sports",
    source: "ESPNcricinfo",
    imageUrl: img("cricket"),
    factScore: 93,
    factLabel: "FACT 93",
    sourceCount: 2,
    status: "approved",
    publishedAt: hoursAgo(26),
  },
  {
    id: "ns-08",
    title: "State rolls out AI tutors in 4,000 government schools",
    summary:
      "The pilot puts adaptive AI tutors into classrooms across four districts, with teachers acting as reviewers. Early trials showed a 18-point gain in maths scores; privacy advocates want audit logs made public.",
    category: "India",
    source: "The Indian Express",
    imageUrl: img("school"),
    factScore: 91,
    factLabel: "FACT 91",
    sourceCount: 3,
    status: "approved",
    publishedAt: hoursAgo(30),
  },
  {
    id: "ns-09",
    title: "Streaming platforms agree to common content ratings from October",
    summary:
      "Major platforms will adopt a unified ratings and parental-control standard, ending years of inconsistent labels. The self-regulatory body says the framework covers 96% of streamed content in the country.",
    category: "Entertainment",
    source: "Variety India",
    imageUrl: img("stream"),
    factScore: 89,
    factLabel: "FACT 89",
    sourceCount: 2,
    status: "approved",
    publishedAt: hoursAgo(34),
  },
  {
    id: "ns-10",
    title: "Green hydrogen hub breaks ground with 1.2 GW electrolyser order",
    summary:
      "Construction began on the country's largest green hydrogen hub, anchored by a 1.2 GW electrolyser order and a port-side ammonia line. The consortium targets first exports by late 2028.",
    category: "Business",
    source: "Reuters",
    imageUrl: img("hydrogen"),
    factScore: 94,
    factLabel: "FACT 94",
    sourceCount: 5,
    status: "approved",
    publishedAt: hoursAgo(40),
  },
];

export const SEED_CONTENT: ContentItem[] = [
  {
    id: "c-qix-1",
    kind: "qix",
    title: "Why the rupee moves when the Fed speaks",
    slug: "rupee-fed-explainer",
    summary:
      "A 90-second explainer on rate differentials, carry trades and why Mumbai wakes up watching Washington.",
    body: { script: "Open on trading floor b-roll..." },
    categorySlug: "business",
    tags: ["economy", "explainer"],
    language: "en",
    state: null,
    coverUrl: img("rupee"),
    mediaUrl: "https://cdn.dailymattr.example/qix/rupee-fed.mp4",
    durationSec: 92,
    sourceLinks: [{ title: "RBI bulletin", url: "https://rbi.org.in" }],
    factScore: 95,
    factLabel: "FACT 95",
    source: "cms",
    sourceArticleId: null,
    status: "published",
    reviewNote: null,
    createdBy: "u-writer",
    reviewedBy: "u-qa",
    publishedBy: "u-editor",
    scheduledAt: null,
    publishedAt: hoursAgo(20),
    createdAt: hoursAgo(50),
    updatedAt: hoursAgo(20),
  },
  {
    id: "c-trax-1",
    kind: "trax",
    title: "The case study: how a 100-year-old brand went direct",
    slug: "heritage-brand-dtc",
    summary:
      "Podcast-style deep dive into a legacy manufacturer's shift to direct-to-consumer, step by step.",
    body: { chapters: ["The moat erodes", "Channel conflict", "The pivot"] },
    categorySlug: "business",
    tags: ["case-study", "audio"],
    language: "en",
    state: null,
    coverUrl: img("podcast"),
    mediaUrl: "https://cdn.dailymattr.example/trax/heritage-dtc.mp3",
    durationSec: 1140,
    sourceLinks: [],
    factScore: null,
    factLabel: null,
    source: "cms",
    sourceArticleId: null,
    status: "in_review",
    reviewNote: null,
    createdBy: "u-writer",
    reviewedBy: null,
    publishedBy: null,
    scheduledAt: null,
    publishedAt: null,
    createdAt: hoursAgo(8),
    updatedAt: hoursAgo(6),
  },
  {
    id: "c-pix-1",
    kind: "pix",
    title: "Monsoon in 6 frames: the week the city went underwater",
    slug: "monsoon-six-frames",
    summary:
      "Six images, six captions — how record rainfall reshaped a city's week.",
    body: { frames: 6 },
    categorySlug: "india",
    tags: ["photo-essay"],
    language: "en",
    state: "Telangana",
    coverUrl: img("monsoon"),
    mediaUrl: null,
    durationSec: null,
    sourceLinks: [],
    factScore: null,
    factLabel: null,
    source: "cms",
    sourceArticleId: null,
    status: "draft",
    reviewNote: null,
    createdBy: "u-writer",
    reviewedBy: null,
    publishedBy: null,
    scheduledAt: null,
    publishedAt: null,
    createdAt: hoursAgo(4),
    updatedAt: hoursAgo(2),
  },
  {
    id: "c-art-1",
    kind: "article",
    title: "Airfares dip 12% as new carriers add monsoon capacity",
    slug: "airfare-dip-monsoon",
    summary:
      "Two new entrants added 400 weekly seats on trunk routes, pulling average fares down 12% month-on-month. Analysts expect the discount war to last through August before festival demand returns pricing power to incumbents.",
    body: {},
    categorySlug: "business",
    tags: ["aviation"],
    language: "en",
    state: null,
    coverUrl: img("airport"),
    mediaUrl: null,
    durationSec: null,
    sourceLinks: [{ title: "DGCA data", url: "https://dgca.gov.in" }],
    factScore: 90,
    factLabel: "FACT 90",
    source: "cms",
    sourceArticleId: null,
    status: "in_review",
    reviewNote: null,
    createdBy: "u-writer",
    reviewedBy: null,
    publishedBy: null,
    scheduledAt: null,
    publishedAt: null,
    createdAt: hoursAgo(7),
    updatedAt: hoursAgo(5),
  },
];

export const SEED_SELECTIONS: ArticleSelection[] = [
  {
    articleId: "ns-01",
    position: 1,
    isFeatured: true,
    selectedBy: "u-editor",
    selectedAt: hoursAgo(2),
  },
  {
    articleId: "ns-04",
    position: 2,
    isFeatured: false,
    selectedBy: "u-editor",
    selectedAt: hoursAgo(2),
  },
];

export const SEED_AUDIT: AuditEntry[] = [
  {
    id: "a-1",
    actorId: "u-editor",
    actorName: "Sravan P",
    action: "published",
    entity: "qix",
    entityTitle: "Why the rupee moves when the Fed speaks",
    createdAt: hoursAgo(20),
  },
  {
    id: "a-2",
    actorId: "u-writer",
    actorName: "Nikita Rao",
    action: "submitted for review",
    entity: "trax",
    entityTitle: "The case study: how a 100-year-old brand went direct",
    createdAt: hoursAgo(6),
  },
  {
    id: "a-3",
    actorId: "u-editor",
    actorName: "Sravan P",
    action: "featured",
    entity: "newsstudio article",
    entityTitle: "Monsoon session opens with heated exchange over exam paper leaks",
    createdAt: hoursAgo(2),
  },
];
