import type {
  ArticleSelection,
  AuditEntry,
  Category,
  CmsUser,
  ContentItem,
  NewsStudioArticle,
} from "./types";

export const DEMO_PASSWORD = "mattr123";

export const SEED_USERS: CmsUser[] = [
  {
    id: "u-admin",
    email: "admin@dailymattr.com",
    fullName: "Aarav Mehta",
    role: "super_admin",
    languages: ["en"],
    states: [],
    isActive: true,
    avatarHue: 222,
  },
  {
    id: "u-editor",
    email: "editor@dailymattr.com",
    fullName: "Sravan P",
    role: "chief_editor",
    languages: ["en", "hi"],
    states: [],
    isActive: true,
    avatarHue: 262,
  },
  {
    id: "u-writer",
    email: "writer@dailymattr.com",
    fullName: "Nikita Rao",
    role: "writer",
    languages: ["en"],
    states: ["Telangana", "Andhra Pradesh"],
    isActive: true,
    avatarHue: 152,
  },
  {
    id: "u-qa",
    email: "qa@dailymattr.com",
    fullName: "Farhan Ali",
    role: "qa",
    languages: ["en"],
    states: [],
    isActive: true,
    avatarHue: 20,
  },
];

export const SEED_CATEGORIES: Category[] = [
  { slug: "india", name: "India", kind: null, sortOrder: 1, isActive: true },
  { slug: "world", name: "World", kind: null, sortOrder: 2, isActive: true },
  { slug: "politics", name: "Politics", kind: null, sortOrder: 3, isActive: true },
  { slug: "business", name: "Business", kind: null, sortOrder: 4, isActive: true },
  { slug: "technology", name: "Technology", kind: null, sortOrder: 5, isActive: true },
  { slug: "science", name: "Science", kind: null, sortOrder: 6, isActive: true },
  { slug: "sports", name: "Sports", kind: null, sortOrder: 7, isActive: true },
  { slug: "entertainment", name: "Entertainment", kind: null, sortOrder: 8, isActive: true },
];

const hoursAgo = (h: number) => new Date(Date.now() - h * 3600_000).toISOString();

const img = (seed: string) => `https://picsum.photos/seed/${seed}/640/400`;

export const SEED_NEWSSTUDIO: NewsStudioArticle[] = [
  {
    id: "ns-01",
    title: "Monsoon session opens with heated exchange over exam paper leaks",
    summary:
      "Parliament's monsoon session began with the Opposition demanding a debate on recurring exam paper leaks. The government said a new integrity framework for national tests will be tabled this week, while student groups continued protests in three states.",
    category: "Politics",
    source: "NDTV",
    imageUrl: img("parliament"),
    factScore: 96,
    factLabel: "FACT 96",
    sourceCount: 4,
    status: "approved",
    publishedAt: hoursAgo(3),
  },
  {
    id: "ns-02",
    title: "Chip startup halts signups as demand for new AI model overwhelms GPUs",
    summary:
      "Days after unveiling its most advanced model, a fast-growing AI lab paused new registrations citing GPU capacity limits. Analysts say the surge underlines how compute, not talent, is now the sector's tightest bottleneck.",
    category: "Technology",
    source: "India Today Tech",
    imageUrl: img("gpu"),
    factScore: 92,
    factLabel: "FACT 92",
    sourceCount: 3,
    status: "approved",
    publishedAt: hoursAgo(5),
  },
  {
    id: "ns-03",
    title: "Tanker attack in Strait of Hormuz raises freight and insurance costs",
    summary:
      "A strike on two tankers pushed war-risk premiums sharply higher and rerouted several shipments around the Cape. Officials said one crew member died; energy markets opened 2% up before easing by noon.",
    category: "World",
    source: "Hindustan Times",
    imageUrl: img("tanker"),
    factScore: 90,
    factLabel: "FACT 90",
    sourceCount: 5,
    status: "approved",
    publishedAt: hoursAgo(9),
  },
  {
    id: "ns-04",
    title: "RBI holds rates, signals patience on inflation glide path",
    summary:
      "The central bank kept the repo rate unchanged for a fourth straight meeting, citing sticky food inflation. Economists now expect the first cut no earlier than the December review, with growth projections held at 6.9%.",
    category: "Business",
    source: "Mint",
    imageUrl: img("rbi"),
    factScore: 97,
    factLabel: "FACT 97",
    sourceCount: 6,
    status: "approved",
    publishedAt: hoursAgo(12),
  },
  {
    id: "ns-05",
    title: "ISRO test-fires reusable lander engine ahead of lunar cargo mission",
    summary:
      "The space agency completed a full-duration burn of its throttleable lander engine, a key step toward the 2027 lunar cargo mission. Engineers called the test 'textbook', with reuse targeted across three flights.",
    category: "Science",
    source: "The Hindu",
    imageUrl: img("isro"),
    factScore: 95,
    factLabel: "FACT 95",
    sourceCount: 3,
    status: "approved",
    publishedAt: hoursAgo(18),
  },
  {
    id: "ns-06",
    title: "National monuments shrink under new order, legal challenges mount",
    summary:
      "A federal order reduced two protected monuments, drawing lawsuits from conservation groups and tribal nations within hours. Legal scholars expect the case to reach the Supreme Court next term.",
    category: "World",
    source: "India Today",
    imageUrl: img("monument"),
    factScore: 88,
    factLabel: "FACT 88",
    sourceCount: 4,
    status: "approved",
    publishedAt: hoursAgo(22),
  },
  {
    id: "ns-07",
    title: "T20 league final draws record streaming audience of 61 million",
    summary:
      "Sunday's final set a concurrent-viewership record as the underdogs chased 204 with an over to spare. Advertisers paid up to 40% more than last season for endgame slots, the broadcaster said.",
    category: "Sports",
    source: "ESPNcricinfo",
    imageUrl: img("cricket"),
    factScore: 93,
    factLabel: "FACT 93",
    sourceCount: 2,
    status: "approved",
    publishedAt: hoursAgo(26),
  },
  {
    id: "ns-08",
    title: "State rolls out AI tutors in 4,000 government schools",
    summary:
      "The pilot puts adaptive AI tutors into classrooms across four districts, with teachers acting as reviewers. Early trials showed a 18-point gain in maths scores; privacy advocates want audit logs made public.",
    category: "India",
    source: "The Indian Express",
    imageUrl: img("school"),
    factScore: 91,
    factLabel: "FACT 91",
    sourceCount: 3,
    status: "approved",
    publishedAt: hoursAgo(30),
  },
  {
    id: "ns-09",
    title: "Streaming platforms agree to common content ratings from October",
    summary:
      "Major platforms will adopt a unified ratings and parental-control standard, ending years of inconsistent labels. The self-regulatory body says the framework covers 96% of streamed content in the country.",
    category: "Entertainment",
    source: "Variety India",
    imageUrl: img("stream"),
    factScore: 89,
    factLabel: "FACT 89",
    sourceCount: 2,
    status: "approved",
    publishedAt: hoursAgo(34),
  },
  {
    id: "ns-10",
    title: "Green hydrogen hub breaks ground with 1.2 GW electrolyser order",
    summary:
      "Construction began on the country's largest green hydrogen hub, anchored by a 1.2 GW electrolyser order and a port-side ammonia line. The consortium targets first exports by late 2028.",
    category: "Business",
    source: "Reuters",
    imageUrl: img("hydrogen"),
    factScore: 94,
    factLabel: "FACT 94",
    sourceCount: 5,
    status: "approved",
    publishedAt: hoursAgo(40),
  },
];

/** Pix seed factory — headline ≤55 chars, exactly three key points. */
const pix = (p: {
  id: string;
  title: string;
  slug: string;
  points: [string, string, string];
  tags: string[];
  cover: string;
  state?: string | null;
  status: ContentItem["status"];
  createdBy?: string;
  reviewedBy?: string | null;
  reviewNote?: string | null;
  publishedBy?: string | null;
  hours: number;
}): ContentItem => ({
  id: p.id,
  kind: "pix",
  title: p.title,
  slug: p.slug,
  summary: p.points.join(" "),
  body: { frames: p.points.length, points: p.points },
  categorySlug: "india",
  tags: p.tags,
  language: "en",
  state: p.state ?? null,
  coverUrl: img(p.cover),
  mediaUrl: null,
  durationSec: null,
  sourceLinks: [],
  factScore: null,
  factLabel: null,
  source: "cms",
  sourceArticleId: null,
  status: p.status,
  reviewNote: p.reviewNote ?? null,
  createdBy: p.createdBy ?? "u-writer",
  reviewedBy: p.reviewedBy ?? null,
  publishedBy: p.publishedBy ?? null,
  scheduledAt: null,
  publishedAt: p.status === "published" ? hoursAgo(p.hours) : null,
  createdAt: hoursAgo(p.hours + 6),
  updatedAt: hoursAgo(p.hours),
});

/** Extra Pix so the QA queue, approved shelf and app feed all have content. */
const SEED_PIX: ContentItem[] = [
  pix({
    id: "c-pix-3",
    title: "Cheetah cubs step out at Kuno for the first time",
    slug: "kuno-cheetah-cubs",
    points: [
      "Four cubs born at Kuno left their enclosure for the open grassland this week.",
      "It is the first litter to survive past six months since the 2022 translocation.",
      "Forest officials will track them by collar for another two seasons.",
    ],
    tags: ["wildlife", "photo-essay"],
    cover: "cheetah-kuno",
    state: "Madhya Pradesh",
    status: "in_review",
    hours: 2,
  }),
  pix({
    id: "c-pix-4",
    title: "Inside the night shift that keeps the city fed",
    slug: "night-shift-market",
    points: [
      "Bowenpally market moves 900 tonnes of produce between 1am and 6am daily.",
      "Nearly 4,000 loaders work the floor, most of them seasonal migrants.",
      "A new cold-storage block cut overnight spoilage by roughly a fifth.",
    ],
    tags: ["cities", "photo-essay"],
    cover: "night-market",
    state: "Telangana",
    status: "in_review",
    hours: 5,
  }),
  pix({
    id: "c-pix-5",
    title: "Six charts on where India's solar power actually goes",
    slug: "solar-power-charts",
    points: [
      "Rooftop solar crossed 17GW installed capacity in the last quarter.",
      "Gujarat and Rajasthan together account for almost half of new additions.",
      "Grid curtailment still wastes an estimated 3% of midday generation.",
    ],
    tags: ["energy", "data"],
    cover: "solar-farm",
    state: null,
    status: "in_review",
    hours: 7,
  }),
  pix({
    id: "c-pix-6",
    title: "The last letterpress in Secunderabad shuts shop",
    slug: "letterpress-shuts",
    points: [
      "The 74-year-old press printed wedding cards for four generations of families.",
      "Its owner is donating the type cases to a design school archive.",
      "Only nine working letterpress units remain across the two Telugu states.",
    ],
    tags: ["culture", "photo-essay"],
    cover: "letterpress",
    state: "Telangana",
    status: "approved",
    reviewedBy: "u-qa",
    hours: 9,
  }),
  pix({
    id: "c-pix-7",
    title: "Monsoon fishing ban lifts: the fleet returns",
    slug: "fishing-ban-lifts",
    points: [
      "About 2,300 boats sailed from Visakhapatnam on the first day of the season.",
      "Diesel subsidy claims must now be filed through the state's new portal.",
      "Catch volumes in the first week ran ahead of last year's opening.",
    ],
    tags: ["coast", "photo-essay"],
    cover: "fishing-boats",
    state: "Andhra Pradesh",
    status: "published",
    reviewedBy: "u-qa",
    publishedBy: "u-editor",
    hours: 14,
  }),
  pix({
    id: "c-pix-8",
    title: "A week inside the Charminar restoration scaffolding",
    slug: "charminar-restoration",
    points: [
      "Conservators are replacing lime plaster on the south-west minaret first.",
      "The 16th-century stucco work is being documented in 3D before any repair.",
      "Public access stays open throughout the 14-month schedule.",
    ],
    tags: ["heritage", "photo-essay"],
    cover: "charminar",
    state: "Telangana",
    status: "rejected",
    reviewedBy: "u-qa",
    reviewNote:
      "Point 3 contradicts the ASI note — access is restricted on weekdays. Please verify and resubmit.",
    hours: 20,
  }),
  pix({
    id: "c-pix-9",
    title: "Bengaluru's lake revival, three years on",
    slug: "bengaluru-lake-revival",
    points: [
      "Eleven of the 27 restored lakes now hold water through the dry months.",
      "Sewage inflow still enters four of them from unconnected storm drains.",
      "Citizen groups log water quality readings every fortnight.",
    ],
    tags: ["environment", "photo-essay"],
    cover: "bengaluru-lake",
    state: "Karnataka",
    status: "in_review",
    hours: 1,
  }),
  pix({
    id: "c-pix-10",
    title: "The women running Kerala's coir cooperatives",
    slug: "kerala-coir-women",
    points: [
      "Around 8,000 women run 62 coir societies across Alappuzha district.",
      "Mechanised spinning lifted daily output per worker roughly threefold.",
      "Export orders shifted towards geotextiles rather than floor mats.",
    ],
    tags: ["work", "photo-essay"],
    cover: "kerala-coir",
    state: "Kerala",
    status: "in_review",
    hours: 3,
  }),
  pix({
    id: "c-pix-11",
    title: "Delhi's winter smog, measured street by street",
    slug: "delhi-smog-street",
    points: [
      "Low-cost sensors on 400 autos mapped PM2.5 across the city for a month.",
      "Readings varied up to fourfold between arterial roads and inner colonies.",
      "The dataset is now open for researchers under a public licence.",
    ],
    tags: ["environment", "data"],
    cover: "delhi-smog",
    state: "Delhi",
    status: "in_review",
    hours: 4,
  }),
  pix({
    id: "c-pix-12",
    title: "Handloom weavers move online, one reel at a time",
    slug: "handloom-weavers-online",
    points: [
      "Pochampally clusters now take a third of their orders through social video.",
      "Weaver collectives share one packing hub to keep shipping costs down.",
      "Average realisation per saree rose after cutting out two middle layers.",
    ],
    tags: ["craft", "photo-essay"],
    cover: "handloom-pochampally",
    state: "Telangana",
    status: "in_review",
    hours: 6,
  }),
  pix({
    id: "c-pix-13",
    title: "Night trains: what the new timetable changes",
    slug: "night-trains-timetable",
    points: [
      "Fourteen overnight services gained an hour of running time from this month.",
      "Two Vande Bharat rakes shift to sleeper configuration on the Nagpur route.",
      "Platform ticket checks tighten at six major junctions after 10pm.",
    ],
    tags: ["transport", "explainer"],
    cover: "night-train",
    state: null,
    status: "approved",
    reviewedBy: "u-qa",
    hours: 8,
  }),
  pix({
    id: "c-pix-14",
    title: "Inside a Chennai flood shelter, hour by hour",
    slug: "chennai-flood-shelter",
    points: [
      "A single school building held 640 people at the peak of the second night.",
      "Volunteers ran a rota of hot meals every four hours from one kitchen.",
      "Most families returned home within nine days of the water receding.",
    ],
    tags: ["cities", "photo-essay"],
    cover: "chennai-flood",
    state: "Tamil Nadu",
    status: "approved",
    reviewedBy: "u-qa",
    hours: 11,
  }),
];

export const SEED_CONTENT: ContentItem[] = [
  ...SEED_PIX,
  {
    id: "c-qix-1",
    kind: "qix",
    title: "Why the rupee moves when the Fed speaks",
    slug: "rupee-fed-explainer",
    summary:
      "A 90-second explainer on rate differentials, carry trades and why Mumbai wakes up watching Washington.",
    body: { script: "Open on trading floor b-roll..." },
    categorySlug: "business",
    tags: ["economy", "explainer"],
    language: "en",
    state: null,
    coverUrl: img("rupee"),
    mediaUrl: "https://cdn.dailymattr.example/qix/rupee-fed.mp4",
    durationSec: 92,
    sourceLinks: [{ title: "RBI bulletin", url: "https://rbi.org.in" }],
    factScore: 95,
    factLabel: "FACT 95",
    source: "cms",
    sourceArticleId: null,
    status: "published",
    reviewNote: null,
    createdBy: "u-writer",
    reviewedBy: "u-qa",
    publishedBy: "u-editor",
    scheduledAt: null,
    publishedAt: hoursAgo(20),
    createdAt: hoursAgo(50),
    updatedAt: hoursAgo(20),
  },
  {
    id: "c-trax-1",
    kind: "trax",
    title: "The case study: how a 100-year-old brand went direct",
    slug: "heritage-brand-dtc",
    summary:
      "Podcast-style deep dive into a legacy manufacturer's shift to direct-to-consumer, step by step.",
    body: { chapters: ["The moat erodes", "Channel conflict", "The pivot"] },
    categorySlug: "business",
    tags: ["case-study", "audio"],
    language: "en",
    state: null,
    coverUrl: img("podcast"),
    mediaUrl: "https://cdn.dailymattr.example/trax/heritage-dtc.mp3",
    durationSec: 1140,
    sourceLinks: [],
    factScore: null,
    factLabel: null,
    source: "cms",
    sourceArticleId: null,
    status: "in_review",
    reviewNote: null,
    createdBy: "u-writer",
    reviewedBy: null,
    publishedBy: null,
    scheduledAt: null,
    publishedAt: null,
    createdAt: hoursAgo(8),
    updatedAt: hoursAgo(6),
  },
  {
    id: "c-pix-1",
    kind: "pix",
    title: "Monsoon in 6 frames: the week the city went underwater",
    slug: "monsoon-six-frames",
    summary:
      "Hyderabad logged 21cm of rain in 36 hours, its wettest spell since 2020. Six lakes crossed full tank level, flooding 40 low-lying colonies. Metro services ran free for two days to clear stranded commuters.",
    body: {
      frames: 6,
      points: [
        "Hyderabad logged 21cm of rain in 36 hours, its wettest spell since 2020.",
        "Six lakes crossed full tank level, flooding 40 low-lying colonies.",
        "Metro services ran free for two days to clear stranded commuters.",
      ],
    },
    categorySlug: "india",
    tags: ["photo-essay"],
    language: "en",
    state: "Telangana",
    coverUrl: img("monsoon"),
    mediaUrl: null,
    durationSec: null,
    sourceLinks: [],
    factScore: null,
    factLabel: null,
    source: "cms",
    sourceArticleId: null,
    status: "draft",
    reviewNote: null,
    createdBy: "u-writer",
    reviewedBy: null,
    publishedBy: null,
    scheduledAt: null,
    publishedAt: null,
    createdAt: hoursAgo(4),
    updatedAt: hoursAgo(2),
  },
  {
    id: "c-pix-2",
    kind: "pix",
    title: "Metro Phase II: what opens first, and when",
    slug: "metro-phase-two-opens",
    summary:
      "The 26km Blue Line extension opens to riders on 2 October. Fares stay capped at ₹60 for the first six months. Four interchange stations link it to the existing Red and Green lines.",
    body: {
      frames: 4,
      points: [
        "The 26km Blue Line extension opens to riders on 2 October.",
        "Fares stay capped at ₹60 for the first six months.",
        "Four interchange stations link it to the Red and Green lines.",
      ],
    },
    categorySlug: "india",
    tags: ["transport", "explainer"],
    language: "en",
    state: "Telangana",
    coverUrl: img("metro-phase-2"),
    mediaUrl: null,
    durationSec: null,
    sourceLinks: [],
    factScore: null,
    factLabel: null,
    source: "cms",
    sourceArticleId: null,
    status: "in_review",
    reviewNote: null,
    createdBy: "u-writer",
    reviewedBy: null,
    publishedBy: null,
    scheduledAt: null,
    publishedAt: null,
    createdAt: hoursAgo(9),
    updatedAt: hoursAgo(3),
  },
  {
    id: "c-art-1",
    kind: "article",
    title: "Airfares dip 12% as new carriers add monsoon capacity",
    slug: "airfare-dip-monsoon",
    summary:
      "Two new entrants added 400 weekly seats on trunk routes, pulling average fares down 12% month-on-month. Analysts expect the discount war to last through August before festival demand returns pricing power to incumbents.",
    body: {},
    categorySlug: "business",
    tags: ["aviation"],
    language: "en",
    state: null,
    coverUrl: img("airport"),
    mediaUrl: null,
    durationSec: null,
    sourceLinks: [{ title: "DGCA data", url: "https://dgca.gov.in" }],
    factScore: 90,
    factLabel: "FACT 90",
    source: "cms",
    sourceArticleId: null,
    status: "in_review",
    reviewNote: null,
    createdBy: "u-writer",
    reviewedBy: null,
    publishedBy: null,
    scheduledAt: null,
    publishedAt: null,
    createdAt: hoursAgo(7),
    updatedAt: hoursAgo(5),
  },
];

export const SEED_SELECTIONS: ArticleSelection[] = [
  {
    articleId: "ns-01",
    position: 1,
    isFeatured: true,
    approvedBy: "u-qa",
    approvedAt: hoursAgo(3),
  },
  {
    articleId: "ns-04",
    position: 2,
    isFeatured: false,
    approvedBy: "u-editor",
    approvedAt: hoursAgo(2),
  },
];

export const SEED_AUDIT: AuditEntry[] = [
  {
    id: "a-1",
    actorId: "u-editor",
    actorName: "Sravan P",
    action: "published",
    entity: "qix",
    entityTitle: "Why the rupee moves when the Fed speaks",
    createdAt: hoursAgo(20),
  },
  {
    id: "a-2",
    actorId: "u-writer",
    actorName: "Nikita Rao",
    action: "submitted for review",
    entity: "trax",
    entityTitle: "The case study: how a 100-year-old brand went direct",
    createdAt: hoursAgo(6),
  },
  {
    id: "a-3",
    actorId: "u-editor",
    actorName: "Sravan P",
    action: "featured",
    entity: "newsstudio article",
    entityTitle: "Monsoon session opens with heated exchange over exam paper leaks",
    createdAt: hoursAgo(2),
  },
];
